### ISSUE TITLE
Is there a ready-made fastapi integration service image?

### ISSUE THREAD

**Issue by yuanjie-ai** [Unstructured-IO/unstructured-api#339]
Is there a ready-made fastapi integration service image?

**Comment by lambda-science** [comment]
```yaml
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - 8002:8002
    entrypoint: ["uvicorn", "prepline_general.api.app:app", "--log-config", "logger_config.yaml",
                 "--host", "0.0.0.0", "--port", "8002"]
```

But it's really huge, like 17go docker image. How can we reduce this
