### ISSUE TITLE
Error in the default docker image when running it with MAX_LIFETIME_SECONDS

### ISSUE THREAD

**Issue by ManuelAngel99** [Unstructured-IO/unstructured-api#469]
**Describe the bug**

<img width="704" alt="image" src="https://github.com/user-attachments/assets/01f106c5-ea94-4fc5-980e-d06827e75261">

The container errors out when using the ```MAX_LIFETIME_SECONDS``` environment variable.

**To Reproduce**

Use the following docker compose file:

```
services:
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:0.0.80
    container_name: unstructured
    restart: always
    ports:
      - 8000:8000
    environment:
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - MAX_LIFETIME_SECONDS=3600
```

And run 
```
docker compose up
```

**Environment:**
- Ubuntu 22.04 LTS, but it also fails in Mac OS X.

**Additional context**
