### ISSUE TITLE
No support for Mac Silicon in Docker download 

### ISSUE THREAD

**Issue by SA-al-000** [Unstructured-IO/unstructured-api#480]
The Docker download does not have any support for Mac OS.

**Comment by tangkunyin** [comment]
> The Docker download does not have any support for Mac OS.

The linux container works well by far

**Comment by dqlobo** [comment]
Here's an example docker compose file:
```
services:
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    container_name: unstructured
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/unstructured-data:/data
    command: ["make", "run-web-app", "--port", "8000"]
```
